routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
	return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('/auth/redirect/{provider}', 'Auth\SocialLoginController@redirectToProvider');
Route::get('/callback/{provider}', 'Auth\SocialLoginController@handleProviderCallback');

Route::resource('user', 'UserController')->except(['show', 'create', 'store'])->middleware('admin:admin');
Route::post('user/{id}/activate', 'UserController@activate')->name('user.activate')->middleware('admin:admin');
Route::get('user/chart/show', 'UserController@chart')->name('user.chart')->middleware('admin:admin');
Route::post('user/{id}/deactivate', 'UserController@deactivate')->name('user.deactivate')->middleware('admin:admin');

Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth:customer', 'check-subscription']);
Route::get('payment', 'SubscribeController@payment')->middleware('auth:customer');
Route::post('subscribe', 'SubscribeController@subscribe')->middleware('auth:customer');

Route::get('admin/login', 'AuthAdmin\LoginController@showLoginForm');
Route::post('admin/login', 'AuthAdmin\LoginController@login')->name('admin.login');
Route::get('admin/logout', function () {
	auth()->guard('admin')->logout();
	return redirect('admin/login');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Cashier\Billable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable,Billable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','social_id','social_type','active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Hash;
use Illuminate\Http\Request;
use Validator;

class UserController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$users = User::when(request()->has('query'), function ($q) {
			$q->where('name', 'LIKE', '%' . request('query') . '%')
				->orWhere('email', 'LIKE', '%' . request('query') . '%');
		})->paginate(30);
		return view('user.index', compact('users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		$user = User::find($id);
		return view('user.edit', compact('user'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		$rules = [
			'name' => ['required', 'string', 'max:255'],
			'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $id],
			'password' => ['required', 'string', 'min:8', 'confirmed'],
		];
		$vresult = Validator::make(request()->all(), $rules);
		if (!$vresult->fails()) {
			$user = User::find($id);
			$update = $user->update([
				'name' => request('name'),
				'email' => request('email'),
				'password' => Hash::make(request('password')),
			]);
			return redirect('/user')->with('success', 'user has been updated');
		} else {
			return redirect('/user/' . $id . '/edit')->with('errors', $vresult->errors());
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		$user = User::find($id);
		$user->delete();
		return redirect('/user')->with('success', 'user has been deleted Successfully');
	}

	/**
	 * deactive the specified user from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function deactivate($id) {
		$user = User::find($id);
		$deactivate = $user->update(
			['active' => false]);
		if ($deactivate) {
			return back();
		}
	}

	/**
	 * active the specified user from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function activate($id) {
		$user = User::find($id);
		$activate = $user->update(['active' => true]);
		if ($activate) {
			return back();
		}
	}

	/**
	 * active the specified user from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function chart() {
		$days = User::selectRaw("DATE(created_at) as day")->pluck('day');
		$data = [];
		foreach ($days as $day) {
			$users = User::whereDate('created_at', $day)->count();
			array_push($data, ['y' => $users, 'label' => $day]);
		}
		$jsonData = json_encode($data, JSON_NUMERIC_CHECK);
		return view('user.chart', compact('jsonData'));
	}

}

resources/views/user/chart.blade.php
@extends('layouts.app')

@section('head')
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
    title: {
        text: "register user of week"
    },
    axisY: {
        title: "Number of users"
    },
    data: [{
        type: "line",
        dataPoints:  {!! $jsonData !!}
    }]
});
chart.render();

}
</script>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div id="chartContainer" style="height: 370px; width: 100%;"></div>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update User</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('user.update',$user->id) }}">
                        @csrf
                        @method('patch')

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text"  class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Update User
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form action="{{ url('/user') }}" method="GET">
                <div class="row mb-2">
                    <div class="col-md-8">
                        <input class="form-control" type="text" placeholder="Search.." value="{{ old('query') }}" name="query">
                    </div>
                    <div class="col-md-4">
                         <button type="submit" class="btn btn-info btn-block">Search</button>
                    </div>
                </div>
            </form>
            <table class="table table-sm">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Active</th>
                    <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                    <th scope="row">{{$user->id}}</th>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    @if($user->active)
                    <td>
                        <form action="{{ route('user.deactivate', $user->id)}}" method="post">
                        @csrf
                            <button type="submit" class="btn btn-dark">InActive</button>
                        </form>
                    </td>
                    @else
                    <td>
                        <form action="{{ route('user.activate', $user->id)}}" method="post">
                        @csrf
                            <button type="submit" class="btn btn-success">Active</button>
                        </form>
                    </td>
                    @endif
                    <td>
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{{ route('user.destroy', $user->id)}}" method="post">
                                @method('DELETE')
                                @csrf
                                <button  type="submit" class="btn btn-danger btn-block" type="submit">Delete</button>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ route('user.edit',$user->id) }}" class="btn btn-warning btn-block">Update</a>
                        </div>
                    </div>
                    </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection